In [1]:
import numpy

In [2]:
arr = numpy.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr *10 #Scaller

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [8]:
arr + 10 #Scaller

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])