In [10]:
my_list = [1,2,3]

In [11]:
import numpy as np

In [12]:
np.array(my_list)

array([1, 2, 3])

In [13]:
arr = np.array(my_list)

In [19]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]

In [20]:
my_mat = [l1,l2,l3]

In [21]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(0,11,2)#up to,but no including,step size

array([ 0,  2,  4,  6,  8, 10])

In [30]:
np.zeros((2,4)) #(rows,columns)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [39]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
np.random.rand(5)

array([0.97967476, 0.87077457, 0.41089723, 0.38480405, 0.09262997])

In [47]:
np.random.rand(5,5)

array([[0.49900491, 0.089015  , 0.44366412, 0.11645729, 0.07240428],
       [0.1338714 , 0.38783804, 0.59054676, 0.72465526, 0.4123775 ],
       [0.31174507, 0.06714161, 0.33924911, 0.08731307, 0.75662134],
       [0.68162873, 0.51056222, 0.9920267 , 0.47932525, 0.87910476],
       [0.09270093, 0.97460866, 0.5375574 , 0.11478991, 0.71430074]])

In [51]:
np.random.randn(2,2)

array([[-1.29226339, -0.8259305 ],
       [ 1.72970396,  0.96150969]])

In [62]:
np.random.randint(0,100,10) # ten random numbers 0-99

array([96, 22, 39,  3, 63, 74, 37, 31, 53, 22])

In [63]:
arr = np.arange(25)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
ranarr = np.random.randint(0,50,10)

In [66]:
ranarr

array([19,  4, 43,  1, 30, 18, 42, 23,  0,  6])

In [70]:
arr.reshape(5,5) #error if the 25 numbers of arr cant be devided like i asked, like 4,10 must be 40 items

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
ranarr.max() #maximum value in ranarr

43

In [72]:
ranarr.min() #minmum value im ranarr

0

In [73]:
ranarr.argmax() #index of max value in ranarr

2

In [76]:
arr = arr.reshape(5,5)

In [78]:
arr.shape

(5, 5)

In [80]:
ranarr.dtype

dtype('int32')