In [1]:
import numpy

In [2]:
arr = numpy.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [11]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = numpy.arange(0,11)

In [15]:
slice_of_arr = arr[0:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:] = 99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy = arr.copy()


In [22]:
arr_copy[:] = 100

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr_2d = numpy.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[2][1] #row,column

40

In [29]:
arr_2d[0] #row

array([ 5, 10, 15])

In [30]:
arr_2d[2,1]

40

In [31]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [32]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [33]:
arr = numpy.arange(1,11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
bool_arr = arr > 5 #return boolean type for all values

In [39]:
bool_arr #saves the result

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [42]:
arr[bool_arr] #RETURN ONLY THE True values

array([ 6,  7,  8,  9, 10])

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[arr<3]

array([1, 2])

In [45]:
arr_2d = numpy.arange(50).reshape(5,10)

In [46]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [52]:
arr_2d[2:4,2:7]

array([[22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36]])

In [55]:
arr_2d *2 #scalar

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [60]:
def func(x):
    return x*2

In [63]:
arr_2d[0][0] = func(4)

In [64]:
arr_2d

array([[ 8,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
arr_2d2 = arr_2d *2

In [71]:
arr_2d2 = arr_2d >2 

In [72]:
arr_2d[arr_2d2]

array([ 8,  3,  4,  5,  6,  7,  8,  9, 11, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])